### ISSUE TITLE
Как лучше по best practice при регистрации возвращять http-код

### ISSUE THREAD

**Issue by KartnDev** [KartonDCP/webmvc-task2#6]
`@ResponseStatus(HttpStatus.CREATED)
    public OrderRegisterResponse registerDo(OrderRegisterRequest orderRequest)` 
    то есть добавить аннотацию `@ResponseStatus(HttpStatus.CREATED)` со статусом 201 при регистрации либо все же как говорилось в курсе многие фронтенд клиенты будут проверять по `response.status === 200 `
    Кстати, у меня неделю вроде первая часть висит, я писал на почту, возможно в спам попало
    Вроде все пофиксил по тикетам
    @coursar

**Comment by coursar** [comment]
![image](https://user-images.githubusercontent.com/3601892/126946034-b0758e2f-df49-4c10-9d14-114cb2ac77ba.png)

Принципиальной разницы нет, нужно ориентироваться на фронт. В качестве примера можно смотреть на REST API GitHub (у них более-менее правильно). В качестве альтернативных реализаций можете смотреть на API банков, там почти везде 200.
